version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipay-back-end-api
    ports:
      - '8003:8003'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shipay